theme: minima

title: Utz's Page
description: A Blog about Stuff and Things, like Mezcal, Asparagus, Tea, Coffee, and other things I like.

header_pages:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog/"
  - title: "Cocktails"
    url: "/cocktails/"
